### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by oioioiio** [strapi-community/strapi-plugin-protected-populate#8] opened 2023-02-24 09:13 UTC
Hi. Thanks for the interesting plugin. I had difficulties while trying to build Strapi after installing the plugin.

`ModuleNotFoundError: Module not found: Error: Package path ./addon/display/placeholder is not exported from package /home/XXX/XXX/node_modules/codemirror`

Also, in what file do I configure the plugin? It's not entirely clear in the documentation.

Strapi v4.6.2
Node v16.19.0

**Comment by Boegie19** [comment] 2023-02-26 13:19
@oioioiio You should rebuild your admin and than it should show a specific tab in what you can do all edits also your error is intresting let me look into if I can replicate it.

**Comment by Boegie19** [comment] 2023-03-03 12:33
I did some testing and I could not reproduce the issue

**Comment by prestonator** [comment] 2023-03-07 01:27
I'm having the same issues as @oioioiio 

And I also think there should be a clearer guide on configuring this plugin, because all I see is the yarn add part and no additional steps. I've deleted the Strapi cache, node_modules, rebuild the admin panel. Alas, the same error keeps popping up.

If I can get this working, I feel like it would be awesome! 

Let me know if you need any information from me to see if there is a problem.

Strapi v4.7.1

`yarn run v1.22.19
$ strapi build
Building your admin UI with development configuration...
ℹ Compiling Webpack
ModuleNotFoundError: Module not found: Error: Package path ./addon/display/placeholder is not exported from package /srv/app/node_modules/codemirror (see exports field in /srv/app/node_modules/codemirror/package.json)`

**Comment by Boegie19** [comment] 2023-03-07 10:13
@prestonator @oioioiio  Okay now  can you give me more information like 

Node.js version:
NPM version:
Strapi version:
Database:
Operating system:

**Comment by Boegie19** [comment] 2023-03-07 15:09
Update just got the issue confirmed on linux

**Comment by Boegie19** [comment] 2023-03-07 15:14
This is a strapi issue will see if I can fix it somehow https://github.com/strapi/strapi/issues/15796

**Comment by prestonator** [comment] 2023-03-08 00:34
@Boegie19 

Here's this info in case you still need it:

Node version: 18.14.2
NPM Version: 9.5.0
Strapi version: 4.7.1
Database: PostgreSQL 15.2
OS: Docker Image from [My Docker Profile](https://hub.docker.com/r/prestonator3000/strapi) not sure what OS sorry :/

**Comment by Boegie19** [comment] 2023-03-24 15:33
This issue is fixed on 4.8.0

**Closed as completed by Boegie19** 2023-03-24 15:33 UTC
